const mockProducts = [
  { woo_product_id: '1', name: 'Dance Workshop Ticket', price: 49.99, stock_quantity: 50, total_sales: 23 },
  { woo_product_id: '2', name: 'Bollywood Fitness Class', price: 29.99, stock_quantity: 30, total_sales: 41 },
  { woo_product_id: '3', name: 'Online Choreography Course', price: 99.99, stock_quantity: 100, total_sales: 12 },
  { woo_product_id: '4', name: 'Dance Studio Membership', price: 149.99, stock_quantity: 20, total_sales: 8 },
  { woo_product_id: '5', name: 'Zumba Class Pack (10)', price: 79.99, stock_quantity: 40, total_sales: 31 },
  { woo_product_id: '6', name: 'Contemporary Dance DVD', price: 19.99, stock_quantity: 75, total_sales: 54 },
  { woo_product_id: '7', name: 'Hip Hop Dance Tutorial', price: 34.99, stock_quantity: 60, total_sales: 67 },
  { woo_product_id: '8', name: 'Salsa Beginner Course', price: 44.99, stock_quantity: 35, total_sales: 19 },
  { woo_product_id: '9', name: 'Kathak Dance Workshop', price: 59.99, stock_quantity: 25, total_sales: 7 },
  { woo_product_id: '10', name: 'Bharatanatyam Basics', price: 69.99, stock_quantity: 20, total_sales: 4 },
  { woo_product_id: '11', name: 'Dance Practice Leggings', price: 24.99, stock_quantity: 100, total_sales: 89 },
  { woo_product_id: '12', name: 'Bollywood Costume Set', price: 89.99, stock_quantity: 15, total_sales: 11 },
  { woo_product_id: '13', name: 'Dance Shoes - Jazz', price: 54.99, stock_quantity: 45, total_sales: 36 },
  { woo_product_id: '14', name: 'Ghungroo Set', price: 14.99, stock_quantity: 80, total_sales: 102 },
  { woo_product_id: '15', name: 'Yoga Mat Premium', price: 39.99, stock_quantity: 55, total_sales: 78 },
  { woo_product_id: '16', name: 'Resistance Band Set', price: 17.99, stock_quantity: 90, total_sales: 143 },
  { woo_product_id: '17', name: 'Dance Water Bottle', price: 12.99, stock_quantity: 120, total_sales: 211 },
  { woo_product_id: '18', name: 'Fitness Tracker Band', price: 34.99, stock_quantity: 30, total_sales: 25 },
  { woo_product_id: '19', name: 'Stretching Guide Book', price: 9.99, stock_quantity: 200, total_sales: 167 },
  { woo_product_id: '20', name: 'Dance Bag - Large', price: 44.99, stock_quantity: 40, total_sales: 33 },
  { woo_product_id: '21', name: 'Ankle Weights Pair', price: 22.99, stock_quantity: 65, total_sales: 58 },
  { woo_product_id: '22', name: 'Mirror Wall Set', price: 129.99, stock_quantity: 10, total_sales: 3 },
  { woo_product_id: '23', name: 'Portable Dance Barre', price: 199.99, stock_quantity: 8, total_sales: 2 },
  { woo_product_id: '24', name: 'Dance Floor Tiles (pack)', price: 89.99, stock_quantity: 12, total_sales: 5 },
  { woo_product_id: '25', name: 'Bluetooth Speaker Mini', price: 29.99, stock_quantity: 50, total_sales: 44 },
  { woo_product_id: '26', name: 'NYC Trip Dance Vlog', price: 7.99, stock_quantity: 999, total_sales: 312 },
  { woo_product_id: '27', name: 'Chicago Dance Guide PDF', price: 4.99, stock_quantity: 999, total_sales: 189 },
  { woo_product_id: '28', name: 'LA Workshop Recap Video', price: 14.99, stock_quantity: 999, total_sales: 97 },
  { woo_product_id: '29', name: 'Solo Travel Dance Journal', price: 19.99, stock_quantity: 50, total_sales: 43 },
  { woo_product_id: '30', name: 'Santa Barbara Vlog Pack', price: 9.99, stock_quantity: 999, total_sales: 76 },
  { woo_product_id: '31', name: 'Pune Dance Scene Guide', price: 6.99, stock_quantity: 999, total_sales: 134 },
  { woo_product_id: '32', name: 'TeamNaach Inspired Routine', price: 24.99, stock_quantity: 999, total_sales: 58 },
  { woo_product_id: '33', name: 'Wedding Dance Prep Pack', price: 49.99, stock_quantity: 30, total_sales: 21 },
  { woo_product_id: '34', name: 'Sangeet Choreography Kit', price: 79.99, stock_quantity: 20, total_sales: 9 },
  { woo_product_id: '35', name: 'Bride Dance Workshop', price: 99.99, stock_quantity: 15, total_sales: 6 },
  { woo_product_id: '36', name: 'Couple Dance Tutorial', price: 39.99, stock_quantity: 25, total_sales: 17 },
  { woo_product_id: '37', name: 'Filter Coffee Mug', price: 12.99, stock_quantity: 100, total_sales: 234 },
  { woo_product_id: '38', name: 'Pune Foodie Guide PDF', price: 4.99, stock_quantity: 999, total_sales: 89 },
  { woo_product_id: '39', name: 'Travel Packing Checklist', price: 2.99, stock_quantity: 999, total_sales: 456 },
  { woo_product_id: '40', name: 'San Diego Beach Guide', price: 5.99, stock_quantity: 999, total_sales: 123 },
  { woo_product_id: '41', name: 'New York City Day Guide', price: 7.99, stock_quantity: 999, total_sales: 201 },
  { woo_product_id: '42', name: 'Instagram Growth eBook', price: 19.99, stock_quantity: 999, total_sales: 345 },
  { woo_product_id: '43', name: 'Content Creator Toolkit', price: 34.99, stock_quantity: 999, total_sales: 167 },
  { woo_product_id: '44', name: 'Reels Strategy Guide', price: 14.99, stock_quantity: 999, total_sales: 289 },
  { woo_product_id: '45', name: 'Dance Hashtag Pack', price: 4.99, stock_quantity: 999, total_sales: 512 },
  { woo_product_id: '46', name: 'Brand Collab Template', price: 9.99, stock_quantity: 999, total_sales: 178 },
  { woo_product_id: '47', name: 'Social Media Calendar', price: 12.99, stock_quantity: 999, total_sales: 234 },
  { woo_product_id: '48', name: 'Caption Writing Guide', price: 7.99, stock_quantity: 999, total_sales: 301 },
  { woo_product_id: '49', name: 'Dance Reel Preset Pack', price: 17.99, stock_quantity: 999, total_sales: 423 },
  { woo_product_id: '50', name: 'Creator Mindset Course', price: 59.99, stock_quantity: 999, total_sales: 88 },
];

module.exports = mockProducts;